[package]
name = "geom2d"
version = "0.1.0"
authors = ["craig fay <craigfay1@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[features]
distance = []
time_of_impact = ["distance"]
default = ["distance", "time_of_impact"]
