[package]
name = "performesh"
version = "0.1.0"
authors = ["craig fay <craigfay1@gmail.com>"]
edition = "2018"
license-file = "LICENSE"

[features]
distance = []
rigid_body = []
time_of_impact = ["distance"]
default = ["distance", "rigid_body", "time_of_impact"]
